### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by jasscia18** [eyecan-ai/eyecandies#1]
Hello, I am very interested in your research, but I can't download your dataset. Do you have any other ways to share your datasets？
<img width="662" alt="1671202721626" src="https://user-images.githubusercontent.com/43958686/208125934-acd8bf52-6f4a-4fcc-9bcc-e9e77129d958.png">

**Comment by LucaBonfiglioli** [comment]
Hello, thank you for reporting this issue! 

While we try to reproduce (and fix) the error, you can still download the dataset manually from our [download page](https://eyecan-ai.github.io/eyecandies/download). There is a google drive link for each object class, containing a .tar file with the dataset.

**Comment by nfioraio-ec** [comment]
You're right, unfortunately we bypass the google drive warning about "large file" using a simple regex and it seems that the html has recently changed. Should be fixed now, so please `git pull` and try again.

**Comment by jasscia18** [comment]
Thank you very much for your help, I have successfully downloaded the dataset. But I'm not sure how to test the results of our training. Is the 00_score within the outputs the result?
![LN_P}2`G22R24FNY}VAV3EF](https://user-images.githubusercontent.com/43958686/208280758-e092494b-c365-46e0-afd6-8cd1043b10f1.png)

**Comment by nfioraio-ec** [comment]
If this is the output of the `predict` command, then `score` is a txt with the maximum absolute difference between the reconstructed image and the public groundtruth. The `predict` command has been written as an example to get the results with a naive autoencoder, so you should write your own command to get the output for your model.

Then, you can use `ec-metrics` to compute the final stats on the public test set. If you want to get the result on the larger private test set, just send us your results as described here https://eyecan-ai.github.io/eyecandies/ following the same format required by `ec-metrics`. A sample submission is here https://drive.google.com/file/d/17qTSfqFesnb5BG6BdgegjWLv7bHKJJMs/view?usp=sharing

Finally, the DAG we provide, ie, `train_predict_stats.yaml` (cfr. https://github.com/eyecan-ai/eyecandies#train-a-model), just show you how to easily run the train-test procedure using [Pipelime](https://pipelime-python.readthedocs.io/en/latest/).
