### ISSUE TITLE
How to convert the depth map to point cloud?

### ISSUE THREAD

**Issue by Leonmel** [eyecan-ai/eyecandies#2]
I noticed that you have provided the pose matrix, can I use this pose to convert the depth map into a point cloud, and if so how?

**Comment by nfioraio-ec** [comment]
Leonmel, you're right, we did not provide the camera matrix to project the metric depth map to 3D. We are adding an example on the project page right now, we'll let you know when it's ready.

**Comment by nfioraio-ec** [comment]
Hi Leonmel, sorry for the late reply but we wanted to add some more doc on the project page and the repo as well. There are some new code snippets on the [download page](https://eyecan-ai.github.io/eyecandies/download) and a new stage. For example, to get a pointcloud with normals and colors:

```{bash}
$ eyec map +i path/to/eyecandies/dataset +o path/to/output/dataset +stage.compose.stages[0] depth2mt +stage.compose.stages[1] depth2pc +g 4,10
```

**IMPORTANT**: you have to pull and **INSTALL** again the package

Hope everything is clear now!
